on:
  push:
    branchs:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - name: checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'yarn'

    - name: Install packages and deploy
      run: |
        yarn install
        git config --local user.email "kbmin1129@gmail.com"
        git config --local user.name "minr2kb"
        yarn deploy
