on:
  push:
    branchs:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - name: checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main
        path: ./main

    - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'

    - name: Install packages
      run: |
        cd ./main
        yarn install
        yarn deploy
